config:
  map:
    default: |-
      version: v1
      flags:
        migStrategy: none
    mig-single: |-
      version: v1
      flags:
        migStrategy: single
    mig-mixed: |-
      version: v1
      flags:
        migStrategy: mixed
